force-app/main/default/objects/BatchInfo__c/BatchInfo__c.object-meta.xml
<CustomObject>
    <label>Batch Info</label>
    <nameField>
        <label>Batch Info Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Batch Infos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BatchInfo__c/fields/Businesshour__c.field-meta.xml
<CustomField>
    <fullName>Businesshour__c</fullName>
    <label>Business Hour</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/DataRepresentation__c.field-meta.xml
<CustomField>
    <fullName>DataRepresentation__c</fullName>
    <label>Data Representation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/Dates__c.field-meta.xml
<CustomField>
    <fullName>Dates__c</fullName>
    <label>Dates</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/Filter_Name__c.field-meta.xml
<CustomField>
    <fullName>Filter_Name__c</fullName>
    <label>Filter Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectFieldType__c.field-meta.xml
<CustomField>
    <fullName>SobjectFieldType__c</fullName>
    <label>Sobject Field Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectFieldValue__c.field-meta.xml
<CustomField>
    <fullName>SobjectFieldValue__c</fullName>
    <label>Sobject Field Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/SobjectRecordType__c.field-meta.xml
<CustomField>
    <fullName>SobjectRecordType__c</fullName>
    <label>Sobject Record Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchInfo__c/fields/WillRefresh__c.field-meta.xml
<CustomField>
    <fullName>WillRefresh__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Will Refresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/FilterDetailControllertest.cls
@istest
public class FilterDetailControllertest
{
 @istest
    public static void ObjectPic()
    {
        BatchInfo__c btchInfo = new BatchInfo__c();
        btchInfo.Businesshour__c = 'Default';
        btchInfo.Dates__c = 'Last 6 Months';
        btchInfo.Filter_Name__c = 'test';
        btchInfo.DataRepresentation__c = '{"Closed":0,"On Hold":0,"Escalated":0,"InProgress":1.18,"New":0}';
        btchInfo.WillRefresh__c = True;
        btchInfo.SobjectFieldValue__c = 'InProgress';
        btchInfo.SobjectFieldType__c = 'Status';
        btchInfo.SobjectRecordType__c = 'Internal';
        insert btchInfo;
          FilterDetailController.getFilterDetail();
          FilterDetailController.getFilterDetailFromName('test','In Minutes');
          FilterDetailController.getFilterDetails(btchInfo.Id,'In Hours');
          FilterDetailController.getFilterDetails(btchInfo.Id,'In Days');
          FilterDetailController.deleteFilter('test');
          FilterDetailController.getDetail('test');
          FilterDetailController.getSearchFilterDetail('test');
          FilterDetailController.getFilterDetails(btchInfo.Id,'In Minutes');
          FilterDetailController.getFDetail('test');
          FilterDetailController.getFDetail(null);
          System.assert(1==1,'List should not be empty');
          
    }
}